version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    # Optional:: for more verbose logs for debugging
    command: [ "postgres", "-c", "log_statement=all" ]

    ports:
      - "4000:5432"

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - ROCKET_DATABASES={postgres={url=postgres://postgres:postgres@postgres/app_db}}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app



# Testing the endpoints<Manual>:: docker-compose exec app curl -X POST 127.0.0.1:8000/rustaceans -H "Content-Type: application/json" -d '{"name": "john doe", "email": "johndoe@test.com"}'
# Specify the binary to run<no_longer_necessary>::docker-compose exec app cargo run --bin server
# Run the cli::docker-compose exec app cargo run --bin cli
# Testing the endpoints:: docker-compose exec app cargo test
# Note:: This appears to only work when using git bash on Windows